### ISSUE TITLE
Cannot install from the web

### ISSUE THREAD

**Issue by Lerwbd** [jamisonderek/flipper-zero-tutorials#26]
Is there a simpler way?

**Comment by jamisonderek** [comment]
What are you trying to install?  Some of the projects in this repo are intended as starting points for projects and some are applications that can run on their own.

**Comment by Lerwbd** [comment]
Hello ! These words are used in translation
I installed it :)))
And the next problem is
My key has signal 434.xx. and it is the rolling code,"xx" which is the frequency change if I read it "RAW" . I can't get that level?....
a honda key. The button on the lock direction is only to find the car in a parking lot.... what else should I do? Thanks, again ! a great app

**Comment by jamisonderek** [comment]
I recommend custom firmware and use their Sub-GHz app.  They have the encoders/decoders for most rolling codes.  Be careful not to desync your fob, as vehicles can sometimes require dealership to resync.  Ideally follow the process to add a new key and then clone that one, since likely you won't be able to use Flipper Zero to start & drive a vehicle, just unlock it (assuming the rolling code encoder is supported.)
